# Gateway Device (local MQTT)
GatewayDevice.host=localhost
GatewayDevice.port=1883
GatewayDevice.enableCrypt=false
GatewayDevice.userToken=
GatewayDevice.authToken=

# Cloud Gateway Service (Ubidots) - Try with TLS
Cloud.GatewayService.host=industrial.api.ubidots.com
Cloud.GatewayService.port=8883  # Changed from 1883 to 8883
Cloud.GatewayService.userToken=BBUS-e501d7a025da4d618ec413b0da13bc04eab
Cloud.GatewayService.authToken=
Cloud.GatewayService.enableCrypt=true  # Changed to true for TLS

# Device settings
device.id=ConstrainedDevice
device.locationID=gatewaydevice001

# Telemetry
pollCycleSecs=60
sensorEmulator.enable=true
systemPerformanceManager.enable=true
